Proceso sin_titulo
	escribir "ESTE PTOGRAMA SUMARA LOS NUMEROS PARES ENTRE 20 Y EL LIMITE QUE INDIQUES"
	ESCRIBIR "INDICA TU LIMITE"
	LEER NUM
	Z<-NUM
	Para NUM<-20 Hasta Z Con Paso 2 Hacer
		SUM<-SUM+NUM
	Fin Para
	ESCRIBIR "LA SUMA DE LOS PAREA EN EL INTERVALO 20-" Z " ES: " SUM
FinProceso
