Proceso sin_titulo
	ESCRIBIR "ESTE PROGRAMA CALCULARA EL FACTORIAL DEL NUMERO QUE INDIQUES"
	ESCRIBIR "INSERTA EL NUMERO A CALCULAR"
	LEER B
	FACT<-1
	IN<-1
	Mientras IN<=B Hacer
		FACT<-FACT*IN
		IN<-IN+1
	Fin Mientras
	ESCRIBIR "TU FACTORIAL SERA: " FACT
FinProceso
